/**
 * Icon - Unified icon component using lucide-react
 *
 * Provides consistent icons across the application.
 */

import React from 'react';
import {
  FileText,
  Search,
  Filter,
  Bookmark,
  Settings,
  Folder,
  X,
  ChevronDown,
  ChevronRight,
  Plus,
  Minus,
  Copy,
  ArrowDown,
  ArrowUp,
  RefreshCw,
  Play,
  Pause,
  Clock,
  Cpu,
  Layers,
  AlignLeft,
  Check,
  AlertCircle,
  Info,
  AlertTriangle,
  Moon,
  Sun,
  Maximize2,
  Minimize2,
  MoreVertical,
  Trash2,
  Edit3,
  Download,
  Upload,
  FolderOpen,
  File,
  List,
  Grid,
  Terminal,
  Bot,
  MessageSquare,
  BarChart2,
  HelpCircle,
  Keyboard,
  Command,
  Loader2,
  Save,
  Undo,
  Redo,
  ArrowRight,
  ArrowLeft,
  Eye,
  EyeOff,
  MousePointer,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  Split,
  Columns,
  Table,
  Bold,
  Italic,
  Underline,
  Link,
  Code,
  Hash,
  AtSign,
  Calendar,
  Clock3,
  Gauge,
  Activity,
  Zap,
  Target,
  Compass,
  Navigation,
  MapPin,
  Flag,
  Tag,
  ToggleLeft,
  ToggleRight,
  Sliders,
  SlidersHorizontal,
  Box,
  Package,
  Inbox,
  Mail,
  Send,
  Paperclip,
  Link2,
  Image,
  Film,
  Music,
  Mic,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothOff,
  Cloud,
  CloudOff,
  HardDrive,
  Server,
  Database,
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldOff,
  Bug,
  Sparkles,
  Wand2,
  Gem,
  Rocket,
  Plane,
  Car,
  Bike,
  Home,
  Building,
  Building2,
  Store,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Percent,
  TrendingUp,
  TrendingDown,
  PieChart,
  LineChart,
  BarChart,
  Users,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Award,
  Trophy,
  Medal,
  Crown,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Laugh,
  LucideProps,
} from 'lucide-react';

export type IconName = keyof typeof iconMap;

const iconMap = {
  fileText: FileText,
  search: Search,
  filter: Filter,
  bookmark: Bookmark,
  settings: Settings,
  folder: Folder,
  x: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  plus: Plus,
  minus: Minus,
  copy: Copy,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  refreshCw: RefreshCw,
  play: Play,
  pause: Pause,
  clock: Clock,
  cpu: Cpu,
  layers: Layers,
  alignLeft: AlignLeft,
  check: Check,
  alertCircle: AlertCircle,
  info: Info,
  alertTriangle: AlertTriangle,
  moon: Moon,
  sun: Sun,
  maximize2: Maximize2,
  minimize2: Minimize2,
  moreVertical: MoreVertical,
  trash2: Trash2,
  edit3: Edit3,
  download: Download,
  upload: Upload,
  folderOpen: FolderOpen,
  file: File,
  list: List,
  grid: Grid,
  terminal: Terminal,
  bot: Bot,
  messageSquare: MessageSquare,
  barChart2: BarChart2,
  helpCircle: HelpCircle,
  keyboard: Keyboard,
  command: Command,
  loader2: Loader2,
  save: Save,
  undo: Undo,
  redo: Redo,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  eye: Eye,
  eyeOff: EyeOff,
  mousePointer: MousePointer,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  rotateCcw: RotateCcw,
  split: Split,
  columns: Columns,
  table: Table,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  link: Link,
  code: Code,
  hash: Hash,
  atSign: AtSign,
  calendar: Calendar,
  clock3: Clock3,
  gauge: Gauge,
  activity: Activity,
  zap: Zap,
  target: Target,
  compass: Compass,
  navigation: Navigation,
  mapPin: MapPin,
  flag: Flag,
  tag: Tag,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  sliders: Sliders,
  slidersHorizontal: SlidersHorizontal,
  box: Box,
  package: Package,
  inbox: Inbox,
  mail: Mail,
  send: Send,
  paperclip: Paperclip,
  link2: Link2,
  image: Image,
  film: Film,
  music: Music,
  mic: Mic,
  volume2: Volume2,
  volumeX: VolumeX,
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  bluetoothOff: BluetoothOff,
  cloud: Cloud,
  cloudOff: CloudOff,
  hardDrive: HardDrive,
  server: Server,
  database: Database,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  shield: Shield,
  shieldOff: ShieldOff,
  bug: Bug,
  sparkles: Sparkles,
  wand2: Wand2,
  gem: Gem,
  rocket: Rocket,
  plane: Plane,
  car: Car,
  bike: Bike,
  home: Home,
  building: Building,
  building2: Building2,
  store: Store,
  shoppingCart: ShoppingCart,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  percent: Percent,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  pieChart: PieChart,
  lineChart: LineChart,
  barChart: BarChart,
  users: Users,
  user: User,
  userPlus: UserPlus,
  userMinus: UserMinus,
  userCheck: UserCheck,
  userX: UserX,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  crown: Crown,
  star: Star,
  heart: Heart,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  laugh: Laugh,
};

export interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName;
  size?: number;
  color?: string;
  className?: string;
  strokeWidth?: number;
}

export const Icon: React.FC<IconProps> = ({
  name,
  size = 16,
  color,
  className = '',
  strokeWidth = 2,
  ...props
}) => {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  return (
    <IconComponent
      size={size}
      color={color}
      className={className}
      strokeWidth={strokeWidth}
      {...props}
    />
  );
};

// Export commonly used icons for direct import
export {
  FileText,
  Search,
  Filter,
  Bookmark,
  Settings,
  Folder,
  X,
  ChevronDown,
  ChevronRight,
  Plus,
  Minus,
  Copy,
  ArrowDown,
  ArrowUp,
  RefreshCw,
  Play,
  Pause,
  Clock,
  Cpu,
  Layers,
  AlignLeft,
  Check,
  AlertCircle,
  Info,
  AlertTriangle,
  Moon,
  Sun,
  Maximize2,
  Minimize2,
  MoreVertical,
  Trash2,
  Edit3,
  Download,
  Upload,
  FolderOpen,
  File,
  List,
  Grid,
  Terminal,
  Bot,
  MessageSquare,
  BarChart2,
  HelpCircle,
  Keyboard,
  Command,
  Loader2,
  Save,
  Undo,
  Redo,
  ArrowRight,
  ArrowLeft,
  Eye,
  EyeOff,
  MousePointer,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  Split,
  Columns,
};
